version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
  demo:
    image: rohitanand650/demo:latest
    container_name: demo
    ports:
      - 8080:8080
