apiVersion: v1
kind: Service
metadata:
  labels:
    name: demo-app-deployment
  name: demo-app-deployment
spec:
  selector:
    app: demo-app
  type: NodePort
  ports:
    - name: demo-app-deployment
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30901