apiVersion: v1
kind: Service
metadata:
  labels:
    name: demo-app-service
  name: demo-app-service
spec:
  selector:
    app: demo-app
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30901